name: CI

on: 
    push: 
        branches: [ master ]

env:
    LOCAL_DOCKER_TAG: spatialformer-docker:latest
    
#Then the workflow get executed followed by several actions.
jobs:
    build-and-publish:
        name: Build Docker image and publish if on main
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v2
                
            -   name: Setup Python
                uses: actions/setup-python@v2
                with:
                    python-version: 3.9
            -   name: List files for debugging
                run: ls -la
                    
            -   name: Build docker image
                run: docker build --build-arg PYPI_TOKEN=${{ secrets.PYPI_TOKEN }} -t $LOCAL_DOCKER_TAG -f ./docker/Dockerfile .

            -   name: check file
                run: docker run spatialformer-docker:latest ls /home/


